[build]
  # Build command for Next.js
  command = "npm run build"

  # Output directory for Next.js static export
  publish = "out"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"

  # Next.js environment variables
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

# Redirects and rewrites for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (for contact form)
[[forms]]
  name = "contact"

# Edge functions configuration (if needed)
[functions]
  directory = "netlify/functions"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
